restaurant-hero done
Tkachenko01001/team-project-1 pull request #16
Opened 2022-12-03 00:31 UTC by Kateryna12

2022-12-03 14:51 UTC, Tkachenko01001 requested changes

2022-12-03 14:51 UTC, Tkachenko01001 commented on src/sass/index.scss
> +@import './restaurant-hero'; // Restaurant page hero
Імпорт має стояти після імпортованого контейнеру

2022-12-03 14:51 UTC, Tkachenko01001 commented on src/index.html
> +    <include src="./partials/restauranthero.html"></include>
Видаліть інклюд з головної сторінки якщо ваша секція відноситься до іншої сторінки

2022-12-03 14:51 UTC, Tkachenko01001 commented on src/partials/restauranthero.html
> +            <h1 class="restaurant-hero__title">Mimiho</h1>
Заголовок має назву Mimino

2022-12-03 14:51 UTC, Tkachenko01001 commented on src/partials/restauranthero.html
> +                    <li class="button__item"><button type="submit" class="button">Переглянути
Кнопка “Переглянути меню” має бути реалізоване як якірне посилання, що веде до відповідної секції сторінки

2022-12-04 09:15 UTC, andrii-doroshenko requested changes

2022-12-04 09:15 UTC, andrii-doroshenko commented on src/partials/restauranthero.html
> +                    <li class="restaurant-button__item"><button type="submit" class="restaurant-button btn">Забронювати
submit мы делаем при отправке форм. тут просто type="button" для открытия модалки

2022-12-04 15:19 UTC, closed without merging