Додано розмітку Footer
Tkachenko01001/team-project-1 pull request #3
Opened 2022-12-01 18:34 UTC by miroha26

2022-12-01 19:30 UTC, Tkachenko01001 commented on src/partials/footer.html
> +                <a href="#" class="social-list__link">Telegram</a>
Посилання на соц. мережі мають вести до стороннього ресурсу в окремій вкладці наприклад  <a href="https://web.telegram.org/k/" class="social-list__link">Telegram</a>

2022-12-01 19:40 UTC, Tkachenko01001 requested changes

2022-12-01 19:40 UTC, Tkachenko01001 commented on src/partials/footer.html
> +                <a href="#" class="social-list__link">Telegram</a>
Посилання на соц. мережі мають вести до стороннього ресурсу в окремій вкладці до href треба додати посилання. Наприклад: href="https://web.telegram.org/k/". Для відкриття посилання в окремій вкладці необхідно до посилання додати атрибут target="_blank"

2022-12-01 19:40 UTC, Tkachenko01001 commented on src/partials/footer.html
> +                <a href="#" class="social-list__link">Facebook</a>
Посилання на соц. мережі мають вести до стороннього ресурсу в окремій вкладці до href треба додати посилання. Наприклад: href="https://web.telegram.org/k/". Для відкриття посилання в окремій вкладці необхідно до посилання додати атрибут target="_blank"

2022-12-01 19:40 UTC, Tkachenko01001 commented on src/partials/footer.html
> +                <a href="#" class="social-list__link">Instagram</a>
Посилання на соц. мережі мають вести до стороннього ресурсу в окремій вкладці до href треба додати посилання. Наприклад: href="https://web.telegram.org/k/". Для відкриття посилання в окремій вкладці необхідно до посилання додати атрибут target="_blank"

2022-12-01 19:40 UTC, Tkachenko01001 commented on src/partials/footer.html
> +        <a href="#" class="footer-logo">Mimino</a>
Посилання логотипу має повертати користувача на головну сторінку index.html

2022-12-01 19:43 UTC, Tkachenko01001 requested changes
Також інші посилання мають вести до відповідної сторінки html, їх необхідно буде додати коли вони з'являться в мені.

2022-12-02 11:14 UTC, andrii-doroshenko commented on src/partials/footer.html
> +            <li class="socials-lict__item">
перевірте правильнісь іменування класів по bem

2022-12-02 11:15 UTC, andrii-doroshenko commented on src/partials/footer.html
> +            <li class="socials-lict__item">
зокрема список socials-list

2022-12-04 09:48 UTC, miroha26 commented on src/partials/footer.html
> +                <a href="#" class="social-list__link">Telegram</a>
Виправила

2022-12-04 09:48 UTC, miroha26 commented on src/partials/footer.html
> +                <a href="#" class="social-list__link">Facebook</a>
Виправила

2022-12-04 09:48 UTC, miroha26 commented on src/partials/footer.html
> +                <a href="#" class="social-list__link">Instagram</a>
Виправила

2022-12-04 09:48 UTC, miroha26 commented on src/partials/footer.html
> +        <a href="#" class="footer-logo">Mimino</a>
Виправила

2022-12-04 09:49 UTC, miroha26 commented on src/partials/footer.html
> +            <li class="socials-lict__item">
Виправила

2022-12-04 15:19 UTC, merged